language: python
python:
    - "3.6.3"
  
script: 
  - python Test.py
 
deploy:
    provider: heroku
    api_key:
        secure: 88bdcc57-3e98-4a7f-bb46-37947561fb33
    app: cicd-test-function
    on:
        repo: eddie221/git_lab
    run:
      - "git remote -v"
      - "config:set DJANGO_SETTINGS_MODULE=Helloworld.production_settings"
      - "ps:scale web=1"
      - "python mysite/manage.py migrate"
      - "open"
    