language: python
rvm:
 - "3.6.3"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: d8738f9b006e6ca4a7665ae1e4f910a21968d591  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master