language: python
python:
  - "3.6.3"
 
install:
  - pip install -r requirements.txt 
  
script: 
  - python Test.py
  
 
deploy:
    provider: heroku
    api_key:
        secure: 88bdcc57-3e98-4a7f-bb46-37947561fb33
    strategy: git
    app: cicd-test-function
    on:
        repo: eddie221/git_lab
    run:
      - "python /manage.py migrate"
      - "python manage.py syncdb --noinput"